
 #  Python Programming
##  Summer Workshop 2018 
## LSU HPC & LONI


<a id="top"></a>
### Login to shelob 

### Start an interactive session
 
### Lauch jupyter notebook  
***

<a id='overview'></a>
# Topics Covered
<font color=blue>
 * [What is Python](#intro)
 * [Python programming basics](#data-type)
 * [Control structures and functions](#control)
 * [Python modules](#module)
 * [Numpy](#numpy)
 * [Plotting](#plot)</font>
<br>

<a id='intro'></a>
## What is Python?

 * A general-purpose programming language (1980) by Guido van Rossum
 * Intuitive and minimal coding
 * Objected-Oriented
 * Interpreted not compiled
 * Interactive
 * Dynamically typed, no type declarations, data type is tracked at runtime
 * Automatic memory management
  <br>

## What is IPython?

 IPython: an interactive command shell for Python (2001) by Fernando Perez
* Enhanced Read-Eval-Print Loop (REPL) environment
* Command tab-completion, color-highlighted error messages..
* Basic Linux shell integration (cp, ls, rm…)
* Great for plotting!
* More information click _[ipython.org](http://ipython.org)_


## Jupyter Notebook 

* Web interface to Python, introduced in 2015 
* Rich text, improved graphical capabilities
* Integrate many existing web libraries for data visualization
* Allow to create and share documents that contain live code, equations, visualizations and explanatory text. 
* Interface with over 40 languages, such as R, Julia and Scala
[back to top](#top)




## Variables 

* Variable type is dynamically determined from the value it is assigned, no data type is declared
* Assign meaningful variable names
* Some keywords are reserved such as ‘print’, ‘assert’,  ‘while’, ‘lambda’. 
* A variable is assigned using the ‘=’ operator 
* Reference of [keys words](https://docs.python.org/2.5/ref/keywords.html)


## Operators 

* Arithmetic operators +, -, *, /, // (integer division for  floating point numbers), ’**’ power
* Boolean operators and, or and not
* Comparison operators >, <, >= (greater or equal), <=
* (less or equal), == equality



<a id='data-type'></a>
## Build-in Data Types   
<font color=blue>
* [Number](#numbers)
* [String](#string)
* [List](#list)
* [Tuple](#tuple)
* [Dictionary](#dic)
* [File](#file)    
 </font>
 [top](#top)

<a id='numbers'></a>
## Numbers

In [ ]:
x = 3
type(x)

In [7]:
y = 3.0
type (y)

float

In [ ]:
z='hello'
type(z)

In [ ]:
int(3.3)

In [ ]:
complex(3)

In [14]:
import math

In [ ]:
abs(-3.3)

In [ ]:
math.sin(60)

In [ ]:
math.sqrt(25)

<a id='string'></a>
## Strings

In [22]:
my_str = 'Hello World'

In [ ]:
print(my_str); len(my_str)

In [ ]:
len(my_str); print(len(my_str))

In [ ]:
#indexing starting at 0
print(my_str[0]); print(my_str[1]); print(my_str[10])

In [ ]:
#string slicing
print(my_str[1:4]); print(my_str[:]); print(my_str[1:])

In [ ]:
#string split
s1, s2 = my_str.split(); print(s1); print(s2)

In [ ]:
#multiple line spanning
multilines= """This is a multi-line
block of sample
 text"""
print(multilines)

In [ ]:
#string formatting
text = "%d pigs in the barn, I’ll %s and %s" %(3,'huff','puff')
print(text)

In [ ]:
total= "my share = %.2f, tip = %d" %(24.5, 5.5)
print(total)

In [ ]:
#more string ops
my_str="Hello World"
my_str.upper(); print(my_str)
print(my_str.isalpha())

print(my_str.isdigit())

<a id='list'></a>
## Lists
* Collection of data [ ]
* Often used to store homogeneous values
    * e.g., Numbers, names with the same data type
* Members are accessed as strings
* Mutable: modify in place without creating a new object


In [ ]:
my_list = [1,2,9,4]
print(my_list)
#how to find out the data type?

In [ ]:
my_list2 = list(range(4))
print(my_list2)

In [ ]:
# access list members by index 
# start at 0, end at n-1
print("1st element =", my_list[0])
print("last element =", my_list[3])

In [ ]:
#Contatenate lists
print(my_list + my_list)
print(my_list *2)
print(my_list *3)

In [ ]:
# iterate list elements
animals = ['dog','cat','horse']
for name in animals:
    print(name)

In [ ]:
for index, name in enumerate(animals):
    print(index, name)

In [ ]:
# modify list
del my_list[0]; print(my_list)
my_list.append(99); print(my_list)
my_list.insert(1, 100); print(my_list)

In [ ]:
#some list funs
my_list.sort(); print(my_list)
my_list.reverse(); print(my_list)

In [ ]:
#more sorting
my_list = ['cats', 'SHEEP','DOGS','horses']
print(sorted(my_list, key=len))
print(sorted(my_list))
print(sorted(my_list, reverse=True))

In [ ]:
sorted(my_list, key=len)

In [ ]:
# sort by lowercase
sorted(my_list, key=str.lower)

In [ ]:
#list comprehension [expr for var in list]
my_list=[2,5,9,1]
square = [x**2 for x in my_list]; print("square =", square)
large = [n for n in my_list if n >= 5]; print('large =',large)

<a id='tuple'></a>
## Tuples
* Not immutable
* Why Tuple?
* Processed faster than lists
* Sequence of a Tuple is protected
* Sequence unpacking

In [ ]:
my_tup = (2, 8, 3, 1)
a,b,c,d = my_tup
print(a, b)

In [ ]:
print(my_tup[0])

<a id='dic'></a>
## Dictionaries
* List of key-value pairs { }
* Unordered collections of objects, not indexed
* Store objects in a random order to provide faster lookup
* Data type are heterogeneous, unlike list
* Element are accessed by a keyword, not index
* Elements are mutable 
* dict = {"key1”: value1,  “key2”: value2} 

In [ ]:
my_dict = {'cats':1, 'dogs':2, 'sheep':3}
print(my_dict)

In [ ]:
print(my_dict['dogs'])

In [ ]:
my_dict['horse'] = 3; print(sorted(my_dict))

In [ ]:
print(my_dict.keys()); print(my_dict.values())

In [ ]:
for key, value in my_dict.items():
    print(key, value)

<a id='file'></a>
## Files
* file open, close, read, write
* file_handle = open(“file_name”, ‘mode’)
    * Modes: 
    * a: append
    * r: read only (error if not existing)
    * w: write only
    * r+: read/write (error if not existing)
    * w+: read/write
    * b: binary
* Python has a built-in garbage collector
* Object memory space is auto reclaimed once a file is no longer in use 
    

In [ ]:
# read a file
input = open("data.txt", 'r')
content = input.read()
input1.close()
print(content)

In [192]:
#write to a file
output = open('write.txt','w')
output.write("Writing to a file")
output.close()

<a id='control'></a>
## Control Structures 
<font color=blue>
* if-else
* for loops, while loops
* break: jump out of the current loop
* continue: jump to the top of next cycle within the loop
* pass: do nothing 
</font> 
[top](#top)

In [ ]:
x = input("Please enter a number")
if ( x >= '5' ):
    print(x,"> 5")
else:
    print(x, "< 5")
    

In [ ]:

for index in range(3):
    print(index)

In [ ]:
index=0
while (index < 3):
    print(index)
    index = index + 1

<div class='alert alert-block alert-danger'>  Tip: <div>
Indentation: signify code blocks  <div>

In [ ]:
#prime numbers
n = 2
while n < 10:
    prime = True
    for x in range(2,n):
        if n % x == 0:
            prime = False
            break
        if prime:
            print(n, 'is a prime #')
            pass
        else:
            n= n + 1
            continu
    n = n + 1

<a id='module'> </a>
## Functions
def func_name(par1, par2,...): 
> body of code
 
 [top](#top)    
    

In [ ]:
#addition
def my_add(x, y):
    return x+y

my_add(3, 8)

In [ ]:
#return multiple values
def power(input):
    return input**2, input**3

square, cube = power(3)
print("squre =",square, "cube =",cube)

<a id='module'> </a>
## Python Module
* A python script with python functions and statements
* Import a module before having access to all the functions within
* Most Python distributions come with plenty of build-in modules 
***
 [top](#top)


## Python Modules
* math, sys, os..
* NumPy, high performance in vector & matrix using vector computation 
* SciPy: based on Numpy, including many scientific algorithms.
* padas
* matplotlib, pyplot, pylab

Reference to [Python3.x standard libraries](https://docs.python.org/3/library/) 


In [ ]:
#import a module
import math
math.sin(math.pi)

In [ ]:
#get information of a module
dir(math)

In [ ]:
#get information
help(math)

In [ ]:
# get information of a module function 
help(math.sin)

 * Examples using os, commands modules
 * os: includes many functions interacting with the file system 


In [ ]:
import os
def display_dir(dir):
      files = os.listdir(dir)
      for fname in files:
        print(fname)
        print(os.path.abspath(os.path.join(dir, fname))) 

display_dir('/tmp')

<a id='numpy'> </a>
## Numpy
* [Create arrays](#array)
* [Properties](#prop)
* [File I/O](#file)
* [Operations](#op)

 [top](#top)
 [next](#plot)

* Provide basic functions for large arrays and matrices
* A Python library that provides a multidimensional array object
* Fast operations on arrays
  * mathematical, logical, shape manipulation 
  * sorting, selecting, I/O
  * discrete Fourier transforms, basic linear algebra
  * basic statistical operations
  * random simulation and much more.

In [ ]:
import numpy as np
a = np.array([4,5,6,7])
b = np.array(range(-1, 3, 1))
print("a",a)
print("b",b)
print("a+b", a+b)
print('a*b', a*b)
for i in range(4):
    print(i)
    

<a id='array'></a>
### Create Arrays

In [ ]:
# create array from a list
a = np.array([2,3,4]); print('a', a)

# arange [start, stop, interval, datatype]
b=np.arange(4, 10.0, 2, np.int64); print("arange",b)

# linspace including both ends {start, stop, num=50, endpoint=True}
c=np.linspace(1,5, 10); print('linspace',c)

# create array on log scale {start, stop, num=50, endpoint=True, base=10}
d=np.logspace(1,100, 5, base=2); print('logspace',d)

# create a square array with ones on the main diagonal
y=np.identity(4); print(y)


# Initialize w/ 0s or 1s
c = np.zeros((2,3)); print("c",c)
d = np.ones((2, 5)); print("d", d); 
a.fill(0); print(a)
a[:] = 1; print(a)



In [ ]:
np.mgrid[0:5, 0:7]
print(a); print(b)

<a id='prop'></a>
### Numpy array properties

In [ ]:
# numpy array properties
print(a.dtype); print(a)
print(a.shape)  # dimensions
print(a.size)   # number of elements
print(a.ndim)   # number of dimensions


<a id='file'></a>
### Numpy File I/O

In [40]:
# comma-separated values (CSV), or related format such as TSV (tab-separated values)
# read data into Numpy arrays using genfromtxt
import numpy as np
!head stock.dat
data=np.genfromtxt('stock.dat', delimiter=','); 
#np.load('stock.dat')


1800  1  1    -6.1    -6.1    -6.1 1
1800  1  2   -15.4   -15.4   -15.4 1
1800  1  3   -15.0   -15.0   -15.0 1
1800  1  4   -19.3   -19.3   -19.3 1
1800  1  5   -16.8   -16.8   -16.8 1
1800  1  6   -11.4   -11.4   -11.4 1
1800  1  7    -7.6    -7.6    -7.6 1
1800  1  8    -7.1    -7.1    -7.1 1
1800  1  9   -10.1   -10.1   -10.1 1
1800  1 10    -9.5    -9.5    -9.5 1


In [41]:
#store and save arrays into a file
m = np.random.rand(4,4); print(m)
np.savetxt('random_m.csv', m, fmt='%.5f')
!cat random_m.csv

[[0.91293621 0.44913208 0.84843745 0.46405243]
 [0.96302897 0.38896432 0.34535125 0.74813727]
 [0.31431767 0.53845025 0.00129205 0.97297451]
 [0.38731484 0.69111267 0.42069492 0.63743375]]
0.91294 0.44913 0.84844 0.46405
0.96303 0.38896 0.34535 0.74814
0.31432 0.53845 0.00129 0.97297
0.38731 0.69111 0.42069 0.63743


In [53]:
#!cat intpython/data.txt
data2=np.genfromtxt('data.txt', skip_header=16, dtype=None, encoding=None)
print(data2)
#help(np.genfromtxt)

[(1,   3.385,  44.5 , 'abjhk') (2,   0.48 ,  33.38, 'bc_00asdk')
 (3,   1.35 ,   8.1 , 'fb') (4, 465.   , 423.  , 'cer')
 (5,  36.33 , 119.5 , 'rg') (6,  27.66 , 115.  , 'rk')
 (7,  14.83 ,  98.2 , 'fff') (8,   1.04 ,   5.5 , 'zxs')
 (9,   4.19 ,  58.  , 'kij')]


In [21]:
data2=np.loadtxt('data.txt', skiprows=16, usecols={0,1,2}, comments='#', dtype=None)


<a id='op'></a>
### Numpy Operations

In [ ]:
#reshape array structures
a=np.arange(32); print(a); print(a.ndim); print(a.shape)
b=a.reshape(4,-1)
print(b); print(b.ndim); print(b.shape)
b.flatten()

In [ ]:
# Indexing from 0:N-1
print(b.size); print(b); print(b.ndim)
print(b[:,0])  # all the rows from 1st colume
print(b[0,:])  # all the columes from 1st row
print(b[0,0])

In [ ]:
# Slicing:to extract part of an array [lower:upper:step]
A = np.array([1,2,3,4,5])
print(A[::])
print(A[::2])
print(A[3:])  #element from index 3
print(A[:3])  #first 3 elements

In [ ]:
# Fancy nndexing: when an array/list is used in place of an index
A=np.array([[n+m*10 for n in range(6)] for m in range(7)]); print(A)
row_index=[1,2,3]
A[row_index]


In [81]:
col_index=[1,2,-1]
A[row_index,col_index]

array([11, 22, 35])

In [ ]:
# Index mask
B=np.array(range(4)); print(B)
row_mask=np.array([True, True, False, False])
B[row_mask]
#row_mask2=np.array([1,1,0,0], dtype=bool)
#B[row_mask2]

#### Element-wise array operations

In [ ]:
!head stock.dat

import numpy as np
data2=np.genfromtxt('stock.dat')
#np.shape(data); print(data);print(data[:,3])
#np.mean(data[:,3]) #temprature data


In [100]:
#standard deviation and variance
np.std(data[:,3]), np.var(data[:,3])  

(4.301174258269478, 18.5001)

In [ ]:
#min, max
data[:,3].min()


#### Data processing


<a id='plot'> </a>
## Python Plotting
 [top](#top)

* matplotlib: library for plotting 2D graphics
* pyplot: a wrapper module to provide Matlab-style interface to matplotlib
* pylab: numpy plus pyplot


In [13]:
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
# Line plot
data=np.linspace(-np.pi, np.pi, 50); 
sin, cos =np.sin(data), np.cos(data)
plt.plot(data, sin, 'b-*', data, cos,'r-s')
plt.title("plot example")
plt.xlabel('x')
plt.ylabel('sin/con')
#figure legend
plt.legend(['sin','cos'])
plt.show()


In [ ]:
#plotting separate figures
plt.figure()
plt.plot(sin, 'r*', label='sin')
plt.legend()
#2nd figure
plt.figure()
plt.plot(cos, 'b+', label='cos')
plt.legend()
plt.clf()
plt.show()
plt.close('all')


In [ ]:
# subplot on the same figure
# subplot(rows, columns, active_plot)
plt.subplot(2,1,1)
plt.plot(sin, 'r-+')
#2nd subplot
plt.subplot(2,1,2)
plt.plot(cos, 'b-o')
#plt.close()
plt.show()

In [ ]:
# Plot a bar chart
x=['Jan', 'Feb', 'Mar', 'Apr']
y=[ 34, 17, 13, 69]
plt.bar(x, y, color='red')
plt.title("Sale by Month")
plt.xlabel('Month')
plt.ylabel('Sale')
plt.show()

In [ ]:
# Plot histograph
import matplotlib
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(19680801)

# example data
mu = 100  # mean of distribution
sigma = 15  # standard deviation of distribution
x = mu + sigma * np.random.randn(437)
#print(x)
num_bins = 50

fig, ax = plt.subplots()

# the histogram of the data
#help(ax.hist)
ax.hist(x, num_bins, density=1)

# add a 'best fit' line
y = ((1 / (np.sqrt(2 * np.pi) * sigma)) *
     np.exp(-0.5 * (1 / sigma * (bins - mu))**2))
ax.plot(bins, y, '--')
ax.set_xlabel('Smarts')
ax.set_ylabel('Probability density')
ax.set_title(r'Histogram of IQ: $\mu=100$, $\sigma=15$')

# Tweak spacing to prevent clipping of ylabel
#.tight_layout()
plt.show()

In [ ]:
# View an image
image = plt.imread('scan.png')

fig, ax = plt.subplots()
ax.imshow(image)
ax.axis('off')  # clear x- and y-axes
